version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql2:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: "ludvig"
      MYSQL_DATABASE: "ak_db"
      MYSQL_PASSWORD: "dev"
      MYSQL_ROOT_PASSWORD: "dev"

volumes:
  mysql2: